# Generated by Django 2.0.9 on 2018-10-18 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='billng_profile',
            new_name='billing_profile',
        ),
    ]
