# Generated by Django 2.0.9 on 2018-10-17 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_auto_20181017_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingprofile',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
