# Generated by Django 2.0.9 on 2018-10-17 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='oder_id',
            new_name='order_id',
        ),
    ]
