# Generated by Django 2.0.9 on 2018-10-17 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_ordermanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderManager',
        ),
    ]
