# Generated by Django 2.0.9 on 2018-10-17 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_cartmodel_subtotal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartmodel',
            options={'verbose_name': 'Cart', 'verbose_name_plural': 'Carts'},
        ),
    ]
